env:
  name: LVAircraftPitch-v4
  due: 60
  dt: 0.01
  reference:
    range: [-5, 5]
    interval: 5
    tau: 0.5

controller:
  sfb:
    Q: [10, 1]
    R: [1]
  se:
#    params: result/2020.11.01.163856/weights.pt
    lr: 0.5
    window: 1.0

result:
  fig:
    show: True
    dtype:
      pitch: True
      elevator: False
      loss: True
      weight: True
  save:
    path: result
    dtype:
      model: True
      csv: True
      fig: True
