env:
  name: LVAircraftPitch-v4
  due: 60
  dt: 0.01
  target:
    range: [-5, 5]
    period: 5
  fail:
    time: 30
    mode: GAIN_REDUCTION
#    mode: STABILITY_LOSS
    value: 0.2
controller:
  sfb:
    Q: [100, 1]
    R: [1]
