env:
  name: LVAircraftPitch-v4
  due: 240
  dt: 0.02
  reference:
    range: [-1, 1]
    interval: 20
    tau: 1.0
    random: False
  fail:
    mode: gain_reduction
    value: [0.3, 0.301]
    time: 120

controller:
  fbc:
    Q: [10, 1]
    R: [1]

  sye:
    type: nonlinear
    dim_state: 2
    dim_action: 1
    units: [8, 8]
    lr: 0.5
    lr_ssl: 0.1
    lr_nlc: 0.05
    window: 1
    decay: 0.9

  fel:
    type: nlc
    dim_reference: 3
    dim_action: 1
    units: [16, 16]
    lr: 0.0001
    lr_lin: 0.00015
    lr_nlc: 0.00005
    window: 1.0
    decay: 1.0

  feles:
    window: 0.5
    simulation:
      num: 10
      due: 1.0
      interval: 0.02
    temp: 5000.0
    threashold: 0.01
    decay: 0.9
    repeat: 3

result:
  path: result/temp
  fig:
    show: True
    save: True
  data: True
