env:
  name: LVAircraftPitch-v4
  due: 2
  dt: 0.02
  reference:
    range: [-5, 5]
    interval: 30
    tau: 0.5





sim:
  due: 1
  dt: 0.02
  reference:
    range: [-5, 5]
    interval: 20
    tau: 1.0

controller:
  sfb:
    Q: [10, 1]
    R: [1]
    repeat: 1
  fel:
    dim_act: 1
    dim_ref: 3
    lr: 0.1
    repeat: 1
  dfel:
    dim_act: 1
    dim_ref: 3
    lr: 0.2
    units: [8, 8]
    repeat: 1
  sye:
    lr: 0.01
    window: 1.0
  feles:
    temp: 5000.0
    threashold: 0.01
    decay: 0.9

result:
  path: result/temp
  fig:
    show: True
    save: True
  data: True
